version: "3"
services:
  redis-server:
    image: redis:latest
  fast-api:
    # image: python:3.11.2
    build: .
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    depends_on:
      - redis-server
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
