name: Python package 

on:   
  pull_request:
    branches:
      - feat/git_action
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    
    steps:
      - name: PR Check
        run: |
          echo The PR was merged
      
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: 'pip'
      - name: Set up venv 
        run: |
          cd backend
          if ![-f .venv]; then python -m venv .venv; fi
          . .venv/bin/activate 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          if [-f requirements.txt]; then pip install -r requirements.txt; fi

      - name: Run the project 
        run: |
          uvicorn app.main:app --reload host=0.0.0.0